### ISSUE TITLE
How to display a PDF label ?

### ISSUE THREAD

**Issue by alfallouji** [alfallouji/DHL-API#6]
Received the following email : 

Hi Bashar,

Your DHL library on GIT will certainly help a lot of folks like me, thanks.

Have a question as when do a Validation request, upon success the XML generated gives binary of barcode and images - do you have any idea how I could show this on a proper PDF file ?

Thanks in advance.

best regards,

Biplov gautam

**Comment by Arti-webkul** [comment]
Thanks for the above guiding.

Kindly help me with an issue of DHL Api.

The issue is when I am sending the request to DHL for getting cost of services provided by DHL like Express Domestic, Express Worldwide etc then I am getting the response as " System Unavailable:DCT webservice host is not reachable " most of the times, also sometimes I got the shipping charges and offered services details too.

That's why It is creating issue.

Please help its urgent.

**Comment by AhlemJH** [comment]
I need the solution in java.
Can you help me please???
