### ISSUE TITLE
AddressLine issue

### ISSUE THREAD

**Issue by sunalan** [alfallouji/DHL-API#7]
Hi Al-fallouji
I try to use multiple line address to shipment request, but it's not work.
It's a sample (sample/GB/ShipmentRequest.php)
There are two address line on your sample code.
$sample->Shipper->AddressLine = '1 New Orchard Road';
$sample->Shipper->AddressLine = 'Armonk';

The result of XML only one line => <AddressLine>Armonk</AddressLine>

How can i use the multiple line of address?

Thank you for your time.

Sincerely,

Alan Sun

**Comment by hsinmaochiu** [comment]
Hi alfallouji , how can I add  “addressline2 “ for Consignee? Because some address street will over 35 chars.

Consignee’s full address 

7311 NW 12th St 7311 NW 12th St Swite 22 # SWxxx22
xxxx
xxxx
xxxx
United States

samples\GB\ShipmentRequest.php
$sample->Consignee->addAddressLine($_GET['address_street']);
$sample->Consignee->City = $_GET['address_city'];//'TAINAN CITY';
$sample->Consignee->PostalCode = $_GET['address_zip_code']; $sample->Consignee->CountryCode = $_GET['Code_Paypal']; 
$sample->Consignee->CountryName = $_GET['address_country']; if($_GET['address_state'] =='US' or $_GET['address_state'] =='CA'){
$sample->Consignee->DivisionCode = $_GET['address_state'];

How does it work? 
$sample->Consignee->addAddressLine($_GET['address_street']);
$sample->Consignee->addAddressLine($_GET['address_street2']);

But I could not get correct xm, no addressline2. Can you help me? 
Request_XML
< Consignee>
  <  CompanyName  >  xxxxxxx  <  CompanyName  >
  <  AddressLine  >7311 NW 12th St 7311 NW 12th St Swite 22 # SWxxx22
 <  AddressLine  >
  <  AddressLine  \ >
  <  City  >  xxx<  City  >
  <  Division  >  xxx<  Division  >
  < PostalCode > xxx < PostalCode >
  < CountryCode >US< CountryCode >
  < CountryName > United States < CountryName >
